version: '3.1'

services:
  gopprof_sidecar_dc:
    container_name: gopprof_sidecar
    entrypoint: pprof
    command: -http=0.0.0.0:10000 targetip:9999/debug/pprof/profile
    # build: .
    image: binacslee/gopprof-sidecar:latest
    volumes:
      - ./:/work
    ports:
        - 10000:10000